/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: '#0d1511',
        'surface-dim': '#0d1511',
        'surface-bright': '#1e2922',
        'surface-container-lowest': '#08100c',
        'surface-container-low': '#151d19',
        'surface-container': '#19211d',
        'surface-container-high': '#242c27',
        'surface-container-highest': '#1a241f',
        'surface-variant': '#1a241f',
        surface: '#0d1511',
        'on-surface': '#e8ede9',
        'on-surface-variant': '#9ab0a2',
        'on-background': '#e8ede9',
        primary: '#5da673',
        'primary-fixed': '#8cd7a0',
        'primary-fixed-dim': '#8cd7a0',
        'primary-container': '#5da673',
        'on-primary': '#00391b',
        'on-primary-container': '#00381a',
        secondary: '#ffb693',
        'secondary-fixed': '#ffdbcc',
        'secondary-fixed-dim': '#ffb693',
        'secondary-container': '#773208',
        'on-secondary': '#562000',
        'on-secondary-container': '#ff9c6b',
        tertiary: '#aacfb7',
        'tertiary-container': '#7c9f89',
        'on-tertiary': '#153726',
        'on-tertiary-container': '#ff9c6b',
        outline: '#404941',
        'outline-variant': '#27342c',
        'amber-threat': '#e66c43',
        brand: {
          50: '#f0fdfa',
          100: '#ccfbf1',
          400: '#8cd7a0',
          500: '#5da673',
          600: '#4a7c59',
          700: '#386345',
          900: '#00391b',
        }
      },
      fontFamily: {
        sans: ['Hanken Grotesk', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
        body: ['Hanken Grotesk', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'telemetry-data': ['JetBrains Mono', 'monospace'],
        'telemetry-metric': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
      }
    },
  },
  plugins: [],
}
